version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb+srv://wolpashka:sholpashka@cluster2.a1p4tuc.mongodb.net/whois_db

    depends_on:
      - db
    volumes:
      - .:/app
  

  db:
    image: mongo:latest
    ports:
      - "27017:27017"  
