version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://db:27017/whois_db
    depends_on:
      - db
    volumes:
      - .:/app
  

  db:
    image: mongo:latest
    ports:
      - "27019:27017"  
